server:
  port: 8081
  servlet:
    context-path: /customerms

spring:
  application:
    name: customerms
  data:
    mongodb:
      uri: mongodb://localhost:27017/
      database: bankingcoredb
      auto-index-creation: true

logging:
  level:
    root: INFO
