# ===============================
# Configuración R2DBC MySQL
# ===============================
spring:
r2dbc:
url: r2dbc:mysql://localhost:3306/accountsdb
username: your_db_username
password: your_db_password
pool:
initial-size: 5
max-size: 20

# ===============================
# Inicialización de esquema
# ===============================
sql:
init:
mode: always
schema-locations: classpath:/schema.sql

# ===============================
# Configuración del servidor
# ===============================
server:
port: 8080

# ===============================
# Logging
# ===============================
logging:
level:
org.springframework.r2dbc: DEBUG
com.example.account: INFO

springdoc:
api-docs:
  path: /api-docs
swagger-ui:
  path: /swagger-ui.html