server:
  port: 8080
  servlet:
    context-path: /bakingapp
spring:
  application:
  name: accounts
  datasource:
    url: jdbc:mysql://localhost:3306/BANKINGCOREDB?useSSL=false&serverTimezone=UTC
    username: root
    password: admin
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
logging:
  level:
    root: INFO




